version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  aws-cli: circleci/aws-cli@2.0.6

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade

  aws-cli-cred-setup:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION


workflows:
  aws-cli:
    jobs:
      - build
      - aws-cli-cred-setup
  maven_test:
    jobs:
      - maven/test