package com.softarum.svsa.modelo.enums;

public enum CodigoEncaminhamento {
	
	SCFV_CRIANCAS_ADOLESCENTES(5),
	SCFV_IDOSOS(6),
	ATZ_CADASTRAL_CADUNICO(7),
	INCLUSAO_CADUNICO(8),
	INSS_INCLUSAO_BPC(9),
	INSS_OUTROS_DIREITOS(10),
	ACESSO_BENEFICIOS_EVENTUAIS(11),
	ACESSO_DOCUMENTACAO_CIVIL_CT_RG_ETC(12),
	//CREAS(13),
	//CRAS(14),
	OUTRAS_UNIDADES_SV_PROTECAO_SOCIAL_ESPECIAL(15),
	
	UNIDADE_PROTECAO_SOCIAL_BASICA(103),
	UNIDADE_PROTECAO_SOCIAL_MEDIA_COMPLEXIDADE(104),
	
	SAUDE_BUCAL(30),
	SAUDE_MENTAL(31),
	SAUDE_ACESSO_PROTESE_PCD(32),
	SAUDE_DA_FAMILIA(33),
	SUS(34),
	
	EDUCACAO_CRECHE_PRE_ESCOLA(40),
	EDUCACAO_REDE_REGULAR_ENSINO(41),
	EDUCACAO_JOVENS_E_ADULTOS(42),
	
	CAPACITACAO_PROFISSIONAL(50),
	TRABALHO_E_RENDA(51),
	INTERMEDIACAO_MAO_OBRA(52),
	MICROCREDITO(53),
	BPC_TRABALHO(54),
	
	PROGRAMA_AREA_HABITACAO(60),
	TARIFA_NACIONAL_ENERGIA_ELETRICA(61),

	CONSELHO_TUTELAR(70),
	PODER_JUDICIARIO(71),
	MINISTERIO_PUBLICO(72),
	DEFENSORIA_PUBLICA(73),
	DELEGACIA(74),	
	/*
	 * Especificos de Salto
	 */
	VIVA_LEITE(100),
	TRANSPORTE_MUNICIPAL_PESSOA_DEFICIENCIA(101),
	VULNERABILIDADE_TEMPORARIA_CESTA_BASICA(102),	
	
	OUTROS_ENCAMINHAMENTOS(85);
	
	private final int valor;
	
	CodigoEncaminhamento(int valor){
		this.valor = valor;
	}	
	
	public int getValor(){
		return valor;
	}

}
