package com.softarum.svsa.modelo.enums;

/**
 * @author gabrielrodrigues
 *
 */
public enum CondicaoOcupacao {
	
	NAO_TRABALHA,
	TRABALHADOR_CONTA_PROPRIA,
	TRABALHADOR_TEMPORARIO_RURAL,
	EMPREGADO_SEM_REGISTRO,
	EMPREGADO_COM_REGISTRO,
	TRABALHADOR_DOMESTICO_SEM_REGISTRO,
	TRABALHADOR_DOMESTICO_COM_REGISTRO,
	TRABALHADOR_NAO_REMUNERADO,
	MILITAR_OU_SERVIDOR_PUBLICO,
	EMPREGADOR,
	ESTAGIARIO,
	APRENDIZ_EM_CONDICAO_LEGAL;
	
}
