package com.softarum.svsa.modelo.enums;

/**
 * @author murakamiadmin
 *
 */
public enum Prioridade {

	SITUACAO_ISOLAMENTO,
	TRABALHO_INFANTIL,
	VIVENCIA_VIOLENCIA_NEGLIGENCIA,
	FORA_ESCOLA_DEFASAGEM_ESCOLAR_MAIOR_2ANOS,
	SITUACAO_ACOLHIMENTO,
	MEDICA_EDUCATICA_MEIO_ABERTO,
	EGRESSO_MEDIDAS_SOCIOEDUCATIVAS,
	SITUACAO_ABUSO_OU_EXPLORACAO_SEXUAL,
	MEDIDA_PROTECAO_ECA,
	CRIANCA_ADOL_SITUACAO_RUA,
	VULNERABILIDADE_DEFICIENTE,
	NAO_HA_SITUACAO_PRIORITARIA
}
