package com.softarum.svsa.modelo.enums;

/**
 * @author gabrielrodrigues
 *
 */
public enum Violencia {
	DISCRIMINACAO_POR_ORIENTACAO_SEXUAL,
	TRABALHO_INFANTIL,
	EXPLORACAO_SEXUAL,
	ABUSO_OU_E_VIOLENCIA_SEXUAL,
	VIOLENCIA_FISICA,
	VIOLENCIA_PSICOLOGICA,
	NEGLIGENCIA_CONTRA_IDOSO,
	NEGLIGENCIA_CONTRA_CRIANÇA,
	NEGLIGENCIA_CONTRA_PCD,
	TRAJETORIA_DE_RUA,
	TRAFICO_DE_PESSOAS,
	VIOLENCIA_PATRIMONIAL_CONTRA_IDOSO_OU_PCD,
	ATO_INFRACIONAL,
	OUTRA;
	
}
